import '../../styles/base.postcss';
import './editor/editor.postcss';
import './toolbar/toolbar.postcss';
import './components/icon/icon.postcss';
import './components/input/input.postcss';
import './components/position/position.postcss';
import './components/size/size.postcss';
import './library/library.postcss';
import './property-panel/property-panel.postcss';
